/*
 * This Scala source file was generated by the Gradle 'init' task.
 */
package phonebook

object App {

  def greeting(): String = "Hello, world!"

  def main(args: Array[String]): Unit = {
    println(greeting())
  }
}
